# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Januri D. P. | Blog
email: januridp@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 The contents of this website are &copy; 2016 under the terms of the MIT License. Powered by Jekyll &amp; Proudly hosted by GitHub.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://januri.github.io" # the base hostname & protocol for your site
twitter_username: januridp
github_username:  januri

# Build settings
markdown: kramdown
